export const ALL_ARMS = Object.freeze({
    'HB1-bind-parser-parity': 'the shared bind parser retains 28 exact Reader cases; Reader H1, H21 and H22 verify startup use and refusals',
    'HT1-token-primitives': 'canonical token decoding, bounded token-file reads and bearer comparison accept only the specified 32-byte token',
    'HT2-tls-primitives': 'TLS arguments preserve both-or-neither diagnostics and malformed material refuses before binding',
    'HH1-route-method': 'exact path and POST-only method refuse before SDK dispatch',
    'HH2-origin-exact': 'Origin matches only the exact serialized allowed value',
    'HH3-declared-length-cap': 'declared oversize body refuses before auth',
    'HH4-streamed-body-cap': 'streamed oversize body refuses before SDK dispatch',
    'HH5-auth-decisions': 'authentication and availability decisions select configured envelopes',
    'HH6-actual-bound-address': 'endpoint metadata and allowed origins use the bound address and port',
    'HH7-response-stream': 'the first Fetch response chunk reaches Node before the held tail',
    'HH8-ordered-shutdown': 'close waits for admitted SDK work before closing the handler',
    'HH9-runtime-server-error': 'an error emitted after listening is handled and begins ordered shutdown',
    'HH10-https-executing-response-during-close': 'an executing TLS request receives its complete response after listener close begins',
    'HH11-declared-upload-413-delivered': 'a real declared oversized upload receives the full 413 refusal before auth or handler dispatch',
    'HH12-chunked-upload-413-delivered': 'a real chunked oversized upload receives the full 413 refusal without handler dispatch',
    'HH13-oversize-drain-deadline': 'an oversized declaration with no upload receives a complete 413 and closes within five seconds',
    'HH14-oversize-drain-concurrency-cap': 'eight concurrent drains deliver the refusal, excess requests close immediately, and a released slot admits another drain',
    'HH15-https-declared-upload-413-delivered': 'a real declared oversized upload over TLS receives the full 413 envelope',
    'HH16-https-chunked-upload-413-delivered': 'a real chunked oversized upload over TLS receives the full 413 envelope',
    'HH17-close-aborts-oversize-drain': 'shutdown during an active drain closes promptly and clears its timer',
    'HH18-route-upload-404-delivered': 'a 1 MiB declared or chunked upload receives the full early 404 refusal in 32 trials',
    'HH19-method-upload-405-delivered': 'a 1 MiB declared or chunked upload receives the full early 405 refusal in 32 trials',
    'HH20-origin-upload-403-delivered': 'a 1 MiB declared or chunked upload receives the full early 403 refusal in 32 trials',
    'HH21-unauth-upload-401-delivered': 'a 1 MiB declared or chunked upload receives the full early 401 refusal in 32 trials',
    'HH22-unavailable-upload-503-delivered': 'a 1 MiB declared or chunked upload receives the full early 503 refusal in 32 trials',
    'HH23-https-route-upload-404-delivered': 'a TLS declared or chunked upload receives the full route refusal in 32 trials',
    'HH24-complete-refusal-no-drain-slot': 'a complete empty-body auth refusal delivers its envelope without taking a drain slot',
    'HH25-internal-upload-500-delivered': 'a held declared or chunked upload receives the full 500 refusal in 32 trials',
    'HH26-reader-listener-state-bounded': '1,000 authenticated Reader reads on distinct connections leave listener tracking empty and retained heap bounded'
});
